name: helio_hi
dependencies:
  - pip==19.3.1
  - pandas==0.25.3
  - scikit-learn==0.20.3
  - numba==0.45.1
  - ipython==7.11.1
  - seaborn==0.9.0
  - matplotlib==3.1.2
  - astropy==4.0
  - scipy==1.3.1
  - numpy==1.17.2
  - scikit-image==0.15.0
